### ISSUE TITLE
Strona główna dla niezalogowanych

### ISSUE THREAD

**Issue by rekah4** [marcin3412/lotek#3]
Należy oprogramować stronę główną portalu dla osób nie zalogowanych. Cały system działania strony zostawiam do własnego wymyślenie. Może to być mvc zrobione w JS albo jaki kolwiek inny wymysł nie opierający się na jakim kolwiek schemacie.
- nie skupiać się na wyglądzie, do tego służą zadania z oznaczeniem STYLOWANIE
#1. Założenia
- [ ] Utworzyć banner lub tekst z możliwością kliknięcia w niego (kliknięcie powoduje przekierowanie na strone główną. To zadanie można wykonać w #4 (napis po lewej))
- [ ] Dodać menu z możliwością zalogowania się oraz rejestracji zadanie #4 #6 #5 (jeżeli zadania nie wykonane zrobić atrape która nigdzie nie przenosi)
- [ ] Menu powinno wyświetlać odpowienie linki w zależności od tego czy jesteśmy zalogowani czy nie. Można to sprawdzić na zasadzie sessji. Jeżeli sessja istnieje to jesteśmy zalogowaniu jeżeli nie to, nie jesteśmy. Tworzenie sessji będzie w zadaniu #6 w tym zadaniu nie zajmujemy się tym. Wystarczy z góry założyć że nie jesteśmy zalogowani if(false) :+1: 

przykład użycia sessji w JQ:

``` javascript
$(function() {
    $.session.set("myVar", "value");
});


// To Read
$(function() {
    alert($.session.get("myVar"));
});
```
- [ ] Kod strony powinien być rozdzielony Osobno style skrypty itd (w miare możliwości)

**Comment by rekah4** [comment]
To zadanie to podstawa, jest potrzebne aby strona zaczeła się wyświetlać po uruchomieniu Projektu.
